# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/ZYNQ_7z020/dma/dma.srcs/sources_1/bd/bd_dma/ip/bd_dma_auto_us_1/bd_dma_auto_us_1.xci
# IP: The module: 'bd_dma_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZYNQ_7z020/dma/dma.gen/sources_1/bd/bd_dma/ip/bd_dma_auto_us_1/bd_dma_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_dma_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/ZYNQ_7z020/dma/dma.gen/sources_1/bd/bd_dma/ip/bd_dma_auto_us_1/bd_dma_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_dma_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/ZYNQ_7z020/dma/dma.srcs/sources_1/bd/bd_dma/ip/bd_dma_auto_us_1/bd_dma_auto_us_1.xci
# IP: The module: 'bd_dma_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZYNQ_7z020/dma/dma.gen/sources_1/bd/bd_dma/ip/bd_dma_auto_us_1/bd_dma_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_dma_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/ZYNQ_7z020/dma/dma.gen/sources_1/bd/bd_dma/ip/bd_dma_auto_us_1/bd_dma_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_dma_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
