# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ZYNQ_7z020/axi_gpio/axi_gpio.srcs/sources_1/bd/bd_axi_gpio/ip/bd_axi_gpio_axi_gpio_0_0/bd_axi_gpio_axi_gpio_0_0.xci
# IP: The module: 'bd_axi_gpio_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZYNQ_7z020/axi_gpio/axi_gpio.gen/sources_1/bd/bd_axi_gpio/ip/bd_axi_gpio_axi_gpio_0_0/bd_axi_gpio_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_axi_gpio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/ZYNQ_7z020/axi_gpio/axi_gpio.gen/sources_1/bd/bd_axi_gpio/ip/bd_axi_gpio_axi_gpio_0_0/bd_axi_gpio_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_axi_gpio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/ZYNQ_7z020/axi_gpio/axi_gpio.gen/sources_1/bd/bd_axi_gpio/ip/bd_axi_gpio_axi_gpio_0_0/bd_axi_gpio_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_axi_gpio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/ZYNQ_7z020/axi_gpio/axi_gpio.srcs/sources_1/bd/bd_axi_gpio/ip/bd_axi_gpio_axi_gpio_0_0/bd_axi_gpio_axi_gpio_0_0.xci
# IP: The module: 'bd_axi_gpio_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZYNQ_7z020/axi_gpio/axi_gpio.gen/sources_1/bd/bd_axi_gpio/ip/bd_axi_gpio_axi_gpio_0_0/bd_axi_gpio_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_axi_gpio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/ZYNQ_7z020/axi_gpio/axi_gpio.gen/sources_1/bd/bd_axi_gpio/ip/bd_axi_gpio_axi_gpio_0_0/bd_axi_gpio_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_axi_gpio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/ZYNQ_7z020/axi_gpio/axi_gpio.gen/sources_1/bd/bd_axi_gpio/ip/bd_axi_gpio_axi_gpio_0_0/bd_axi_gpio_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_axi_gpio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
