# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_axi_gpio.xdc

# Block Designs: bd/bd_axi_gpio/bd_axi_gpio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio || ORIG_REF_NAME==bd_axi_gpio} -quiet] -quiet

# IP: bd/bd_axi_gpio/ip/bd_axi_gpio_processing_system7_0_0/bd_axi_gpio_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_processing_system7_0_0 || ORIG_REF_NAME==bd_axi_gpio_processing_system7_0_0} -quiet] -quiet

# IP: bd/bd_axi_gpio/ip/bd_axi_gpio_rst_ps7_0_50M_0/bd_axi_gpio_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_rst_ps7_0_50M_0 || ORIG_REF_NAME==bd_axi_gpio_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/bd_axi_gpio/ip/bd_axi_gpio_ps7_0_axi_periph_0/bd_axi_gpio_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_axi_gpio_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_axi_gpio/ip/bd_axi_gpio_axi_gpio_0_0/bd_axi_gpio_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_axi_gpio_0_0 || ORIG_REF_NAME==bd_axi_gpio_axi_gpio_0_0} -quiet] -quiet

# IP: bd/bd_axi_gpio/ip/bd_axi_gpio_auto_pc_0/bd_axi_gpio_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_auto_pc_0 || ORIG_REF_NAME==bd_axi_gpio_auto_pc_0} -quiet] -quiet

# XDC: e:/ZYNQ_7z020/axi_gpio/axi_gpio.gen/sources_1/bd/bd_axi_gpio/bd_axi_gpio_ooc.xdc
