# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/ZYNQ_7z020/axi_xadc/axi_xadc.srcs/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_xadc_wiz_0_1/axi_xadc_bd_xadc_wiz_0_1.xci
# IP: The module: 'axi_xadc_bd_xadc_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZYNQ_7z020/axi_xadc/axi_xadc.gen/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_xadc_wiz_0_1/axi_xadc_bd_xadc_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_xadc_bd_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/ZYNQ_7z020/axi_xadc/axi_xadc.gen/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_xadc_wiz_0_1/axi_xadc_bd_xadc_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_xadc_bd_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/ZYNQ_7z020/axi_xadc/axi_xadc.srcs/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_xadc_wiz_0_1/axi_xadc_bd_xadc_wiz_0_1.xci
# IP: The module: 'axi_xadc_bd_xadc_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZYNQ_7z020/axi_xadc/axi_xadc.gen/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_xadc_wiz_0_1/axi_xadc_bd_xadc_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_xadc_bd_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/ZYNQ_7z020/axi_xadc/axi_xadc.gen/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_xadc_wiz_0_1/axi_xadc_bd_xadc_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_xadc_bd_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
