# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/axi_xadc_xdc.xdc

# Block Designs: bd/axi_xadc_bd/axi_xadc_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_xadc_bd || ORIG_REF_NAME==axi_xadc_bd} -quiet] -quiet

# IP: bd/axi_xadc_bd/ip/axi_xadc_bd_processing_system7_0_0/axi_xadc_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_xadc_bd_processing_system7_0_0 || ORIG_REF_NAME==axi_xadc_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_xadc_bd/ip/axi_xadc_bd_xadc_wiz_0_1/axi_xadc_bd_xadc_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_xadc_bd_xadc_wiz_0_1 || ORIG_REF_NAME==axi_xadc_bd_xadc_wiz_0_1} -quiet] -quiet

# IP: bd/axi_xadc_bd/ip/axi_xadc_bd_ps7_0_axi_periph_1/axi_xadc_bd_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_xadc_bd_ps7_0_axi_periph_1 || ORIG_REF_NAME==axi_xadc_bd_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/axi_xadc_bd/ip/axi_xadc_bd_rst_ps7_0_50M_1/axi_xadc_bd_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_xadc_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==axi_xadc_bd_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/axi_xadc_bd/ip/axi_xadc_bd_auto_pc_0/axi_xadc_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_xadc_bd_auto_pc_0 || ORIG_REF_NAME==axi_xadc_bd_auto_pc_0} -quiet] -quiet

# XDC: e:/ZYNQ_7z020/axi_xadc/axi_xadc.gen/sources_1/bd/axi_xadc_bd/axi_xadc_bd_ooc.xdc
