# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bd_dma/bd_dma.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma || ORIG_REF_NAME==bd_dma} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_processing_system7_0_0/bd_dma_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_processing_system7_0_0 || ORIG_REF_NAME==bd_dma_processing_system7_0_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_axi_dma_0_0/bd_dma_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_axi_dma_0_0 || ORIG_REF_NAME==bd_dma_axi_dma_0_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_ps7_0_axi_periph_0/bd_dma_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_ps7_0_axi_periph_0 || ORIG_REF_NAME==bd_dma_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_rst_ps7_0_50M_0/bd_dma_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_rst_ps7_0_50M_0 || ORIG_REF_NAME==bd_dma_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_axi_mem_intercon_0/bd_dma_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_axi_mem_intercon_0 || ORIG_REF_NAME==bd_dma_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_xlconcat_0_0/bd_dma_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_xlconcat_0_0 || ORIG_REF_NAME==bd_dma_xlconcat_0_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_xbar_0/bd_dma_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_xbar_0 || ORIG_REF_NAME==bd_dma_xbar_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_axis_data_fifo_0_0/bd_dma_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_axis_data_fifo_0_0 || ORIG_REF_NAME==bd_dma_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_auto_pc_0/bd_dma_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_auto_pc_0 || ORIG_REF_NAME==bd_dma_auto_pc_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_auto_us_0/bd_dma_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_auto_us_0 || ORIG_REF_NAME==bd_dma_auto_us_0} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_auto_us_1/bd_dma_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_auto_us_1 || ORIG_REF_NAME==bd_dma_auto_us_1} -quiet] -quiet

# IP: bd/bd_dma/ip/bd_dma_auto_pc_1/bd_dma_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dma_auto_pc_1 || ORIG_REF_NAME==bd_dma_auto_pc_1} -quiet] -quiet

# XDC: e:/ZYNQ_7z020/dma/dma.gen/sources_1/bd/bd_dma/bd_dma_ooc.xdc
