# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ZYNQ_7z020/axi_xadc/axi_xadc.srcs/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_processing_system7_0_0/axi_xadc_bd_processing_system7_0_0.xci
# IP: The module: 'axi_xadc_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZYNQ_7z020/axi_xadc/axi_xadc.gen/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_processing_system7_0_0/axi_xadc_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_xadc_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/ZYNQ_7z020/axi_xadc/axi_xadc.srcs/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_processing_system7_0_0/axi_xadc_bd_processing_system7_0_0.xci
# IP: The module: 'axi_xadc_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZYNQ_7z020/axi_xadc/axi_xadc.gen/sources_1/bd/axi_xadc_bd/ip/axi_xadc_bd_processing_system7_0_0/axi_xadc_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_xadc_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
